let en = {
  general: {
    general_error: 'Oops! Something went wrong',
    eighteen_plus: 'You must be at least 18 years old to use this service.',
    error_server: 'Error at server.Pls retry',
    error_server_message:
      'If issue is presisting contact WAXPLACE ADMIN at email address contact@waxplace.co\nMention the Transaction ID for the failed transaction:',
    error_checkout_message:
      'Please wait for few minutes for us to check your payment. if issue still persists contact WAXPLACE ADMIN at email address contact@waxplace.co\nMention the Transaction ID for the failed transaction:',

    payment_failed: 'Payment is not successful',
    retry_text: 'Would you like to retry?',
    card_failed: 'Card failed,Please retry with a valid card',
    enter_valid_card: 'Please enter valid card details',
    enter_valid_cvv: 'Please enter a valid cvv',
    manage_bank_info: 'MANAGE BANK INFO',
    manage_your_cards: 'MANAGE YOUR CARDS',
    remove_card: 'Remove Card',
    remove_card_text: 'Are you sure you want to remove this card?',
    card_info: 'Card Info',
    saved_cards: 'SAVED CARDS',
    enter_cvv_continue: 'Enter CVV to continue',
    search: 'Search...',
    send_otp: 'Send authentication',
    resend_otp: 'Resend authentication in',
    packaging_info: 'Packaging Information',
    payment_settings: 'PAYMENT SETTINGS',
  },
  payments: {
    KycManager: {
      kyc: 'KYC',
      kyc_document: 'KYC Document',
      kyc_info:
        ' KYC stands for “know your customer” and entails the whole verification process of your users. This process is part of European anti-money laundering regulation, known as AML, which requires institutions such as WAXPLACE to make sure that money transacting through their system is legitimate. It will therefore be an integral part of your collaboration with us.',
      required_document: 'Required Document',
      identity_proof: '(IDENTITY PROOF)',
      identity_proof_info:
        'ID card or passport or driving licence or residency card for European Economic Area (EEA)\n\nID card or passport or driving licence for UK, USA, and Canada\n\nA passport is required for other countries',
      file_size_info: '* File size between 32KB and 8MB\n  are only accepted',
      kyc_updated: 'KYC document submitted successfully',
      invalid_document_size: 'Invalid document size',
      select_kyc_document: 'Please select a valid KYC document',
      submit_kyc_document: 'Submit KYC Document',
      alert_account_number: 'Enter account number',
      camera: 'Camera',
      gallery: 'Gallery',
      select_pdf: 'Select PDF',
      if_not_validating:
        'In order to effectively assess whether documents are genuine or not we must receive good quality documents.',
      if_validating:
        'Please wait while the submitted KYC document(Identity Proof) is being validated.This proccess can take upto 24hrs to complete',
      if_not_validating_second_text:
        'Note : if you are sending several infos for the same document (eg the front and back of a document), you must send one KYC document which contains several pages since each document is processed independantly',
      if_validating_second_text:
        'If validation is completed you will be automatically redirected to the bank accounts and cards management page',
    },
    BankAccountManager: {
      alert_username: "Enter user's name",
      alert_address: 'Enter address',
      alert_country: 'Enter country',
      alert_city: 'Enter city',
      alert_postalcode: 'Enter postal code',
      alert_iban: 'Enter IBAN',
      alert_bic: 'Enter BIC',
      alert_account_number: 'Enter account number',
      alert_aba: 'Enter ABA',
      alert_branch_code: 'Enter branch code',
      alert_institution_number: 'Enter institution number',
      alert_bankname: 'Enter bank name',
      alert_sortcode: 'Enter sort code',
      save_account: 'Save Account',
      select_bank_type: 'Select Bank Type',
      account_exists: 'Account already exists',
    },
  },
  HelperFunctions: {
    permission_message: 'Please grant WAXPLACE access to use the location',
    unable_open_settings: 'Unable to open Settings',
    location_enable:
      'We can´t access your location! Click OK to open settings and enable',
    location_enable_one: `Allow WAXPLACE to use your location`,
    goto_settings: 'Go to Settings',
    dont_use_location: 'Do NOT use my location!',
    distance: 'DISTANCE',
    price_low_high: 'PRICE: LOW TO HIGH',
    price_high_low: 'PRICE: HIGH TO LOW',
    newest: 'NEWEST FIRST',
  },
  _routes: {
    no_internet: 'You have a serious lack of internet connection',
    check_internet:
      'Please check your internet connection, or wifi connection.',
    go_to_settings: 'GO TO SETTINGS',
    home: 'HOME',
    waxmap: 'WAXMAP',
    profile: 'PROFILE',
  },
  components: {
    home: 'HOME',
    waxmap: 'WAXMAP',
    profile: 'PROFILE',
    sell_item: 'Sell Item',
    buy_item: 'Buy Item',
    //SORT VIEW
    sort_by: 'SORT BY',
    reset_filter: 'Reset filter',
    distance: 'Distance',
    price_low_high: 'PRICE: LOW TO HIGH',
    price_high_low: 'PRICE: HIGH TO LOW',
    newest_first: 'Newest first',
    //THREEWAYSWITCH
    choose_style: 'Choose a style',
    auto: 'Auto',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
  },
  chatBot: {
    // ChatScreen //
    shipment_not_yet_created: 'Shipment has not been initialized yet',
    return_request_placed:
      'Return request has been placed.\nCommunicate with support for more info.',
    return_store_info: 'Return process is not valid for store pickup',
    return_24:
      'Return cannot be intiated after 24Hrs of delivery of the album.',
    return_rejected:
      'Return has been rejected by the support,\nafter reviewing your request.',
    return_before_delivery: 'Return process cannot be initiated at the moment',
    chat_disabled: 'Waxplace chat has been disabled',
    // AUDIO BUBBLE //
    discard: 'Discard',
    record_audio: 'Record an audio message',
    confirm: 'Confirm',
    cancel: 'Cancel',

    // IMAGE BUBBLE //
    add_image: 'ADD IMAGE',

    // CANCELSHIPMENT BUBBLE //
    cancel_message: 'Would you like to cancel the purchase of this album?',
    purchase_cancelled: 'Purchase of album has been cancelled',
    order_rejected: 'Order has been rejected by the seller',
    shipment_not_started: 'Shipment of album has been initialized',
    shipment_completed: 'Shipment of album has been completed',
    //TOAST MESSAGE
    cancel_proceed: 'Do you wish to proceed with cancellation?',
    cancel_success: 'Album purchase has been cancelled',

    // RETURN DETAILS BUBBLE //
    return_message: 'Would you like to return this album?',
    wrong_product: 'Wrong Product',
    damaged_product: 'Damaged Product',
    record_audio_complaint: 'Record audio for your complaint',
    discard: 'Discard',
    album_not_delivered: 'Album has not been delivered',
    confirm_return: 'Confirm Return',
    return_initialized: 'Return Process has been initialized',
    //TOAST MESSAGE
    alert_image: 'Please input image description',
    alert_audio: 'Please input audio description',
    alert_return: 'Do you wish to proceed with return?',

    // TRACKING BUBBLE //
    shipment_details: 'Shipment Details',
    shipment_status: 'Shipment Status',
    event_date: 'Event Date',
    event_time: 'Event Time',
    info: 'Info',
    status: 'Status',
  },
  homePage: {
    button_text: 'Explore',
    search_waxplace: 'SEARCH IN WAXPLACE',
    search_in: 'SEARCH IN',
    home: 'HOME',
    button_text: "LET'S GO!",
    skip: 'SKIP',
    featured_items: 'FEATURED ITEMS',
    premium_items: 'PREMIUM ITEMS',
    premium_24: 'PREMIUM 24HR ACCESS',
    empty_text: `You have a great choice;however,\nwe are currently out of stock on certain genre;\nWe will bring in more stocks soon.`,
    not_openable:'Sorry currently unaccessible'
  },
  AlbumDetails: {
    seller_details: 'Seller Details',
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    button_text_three: 'View',
    search_text: 'ALBUM DETAILS',
    tracks: 'Tracks',
    report: `Report`,
    report_text: 'Share your thoughts',
    other_options: 'Other Options',
    submit: 'Submit',
    watch: 'Watch',
    url_unavailable: 'Video Url unavailable',
  },
  Cart: {
    search_text: 'SEARCH IN CART',
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    buy_from: 'Buy from',
    amount: 'Amount',
    hmm: `hmmmm....`,
    have_sharecode: 'Have Share Code?',
    free_token: 'FREE TOKEN',
    empty_cart: `Your shopping cart is currently empty,\nBrowse more items for your ears`,
    empty_button: 'Explore',
    total: 'Total',
    button_text_one: 'Select Store',
    button_text_two: 'Proceed',
    share_code: 'SHARE CODE',
    enter_share_code: 'Enter share code',
    share_code_error: 'Invalid Share Code',
    cancel: 'Cancel',
    apply: 'Apply',

    //TOAST MESSAGES
    select_to_continue: 'Please select an album to continue',
  },
  Categoires: {
    let_us_know: 'LET US KNOW',
    your_vibe: 'YOUR VIBE',
    select_categories:
      'Select some catagories,\nthese will appear in your feed.',
    button_text: 'NEXT',

    //TOAST MESSAGES
    mandatory_to_continue: 'Atleast 3 categories are mandatory to continue.',
  },
  Checkout: {
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    unavailable: 'Currently unavailable',
    one_item: '1 item',
    shipment_short_form: 'Shp.',
    tax: 'Tax',
    amount: 'Amount',
    search_text: 'Buy Albums',
    checkout: 'Checkout',
    total: 'Total',
    pick_from: 'Pickup from',
    return_policy: '* Return not applicable for store pickup',
    pickup_message:
      'You Will Receive A Notification When Your Records Is 24hrs From In Shop & You Can Schedule Your Precise Pick Up.',
    button_text: 'PLACE YOUR ORDER',

    //TOAST MESSAGES
    timeout: 'Checkout has been Timeout',
    no_product: 'No albums available for purchase',
    tax_failed: 'Tax calculation failed.Please recheck page',
    request_reject: 'Request is taking too long to response',
    network_failure: 'Network failed.\nPayment in processing',
    purchase_successful: 'Purchase Successful',
  },
  Collections: {
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    for_sale: 'For Sale',
    active: 'Active',
    feature_now: 'Feature Now',
    select_categories: 'Select Categories',

    cancel_button: 'Cancel Button',
    button_text_one: 'ADD',
    button_text_two: 'FEATURE NOW',
    button_text_three: 'UNFEATURE NOW',
    button_text_four: `BUY TOKENS`,
    feature_item: 'Feature your item',
    unfeature_item: 'Unfeature your item',
    upgrade: 'Upgrade now!!',
    tokens_available: 'YOU HAVE TOKENS\nAVAILABLE',
    deactivate: 'Deactivate now',

    //TOAST MESSAGES
    remove_sales: 'Do you wish to remove this album from sales?',
    add_sales: 'Do you wish to sell this album?',
  },
  CreateSaleProduct: {
    principal: 'Principal',
    feature_item: 'Feature your item',
    upgrade: 'Upgrade now!!',
    tokens_available: 'YOU HAVE TOKENS\nAVAILABLE',
    appear_tokens: 'TOKENS TO APPEAR IN\nFEATURED ITEMS',
    feature_vinyl: 'GET 24 HOUR ACCESS TO\nVINYL BEFORE ANY OTHER\nUSER',
    twentfour_hour: '24 HOUR ACCESS',
    deactivate: 'DeActivate now',
    packaging_info: 'Packaging Instructions',
    button_text_one: `UPGRADE NOW FOR \u20AC${'5,00'}`,
    button_text_two: `BUY TOKENS`,
    button_text_three: 'FEATURE NOW',
    button_text_four: 'UNFEATURE NOW',
    button_text_five: 'Next',
    pm: 'pm',
    or: 'OR',
    purchase_tokens: 'PURCHASE TOKENS',
    ten_tokens: '10 TOKENS',
    twenty_tokens: '20 TOKENS',
    thirty_tokens: '30 TOKENS',
    save28: '',
    save39: '',

    feature_item: 'Feature your item',
    unfeature_item: 'Unfeature your item',
    upgrade: 'Upgrade now!!',
    tokens_available: 'YOU HAVE TOKENS\nAVAILABLE',
    deactivate: 'DeActivate now',
    camera: 'CAMERA',
    gallery: 'GALLERY',
    edit_album: 'EDIT ALBUM',
    add_album: 'ADD ALBUM',
    albumName: 'Album Name',
    artist: 'Artist',
    label: 'label',
    year: 'Year',
    category: 'Category',
    cost: 'Cost',
    tracks: 'Tracks',
    videourl: 'Video URL',
    notes: 'Notes',
    sizeweight: 'Size & Weight',
    select_categories: 'Select Categories',

    mediacondition: 'Media Condition',
    sleevecondition: 'Sleeve Condition',
    continue_collections: 'Continue to collections',
    insufficient_tokens: 'Insufficient tokens',
    //TOAST MESSAGES
    alert_correos_postalCode:
      'The entered Postalcode is not available for shipment',
    alert_albumName: 'Enter album name',
    alert_artist: 'Enter artist name',
    alert_label: 'Enter a label',
    alert_year: 'Enter year',
    alert_cost: 'Enter album cost',
    alert_category: 'Select a category',
    alert_videourl: 'Enter valid Video URL',
    alert_notes: 'Enter notes',
    alert_notes_length: 'Max notes size is 1000 charactes',
    alert_tracks: 'Enter tracks details',
    alert_images: 'Enter atleast two album images',
  },
  DeleteAccount: {
    wish_continue: 'Do you wish to continue?',
    otp_message:
      'Authentification message has been sent to your registerd email.Please verify yout email to continue',
    resend_otp: 'Send authentification',
    button_text_one: 'Delete Permenantly',
    delete: 'Delete Account',
    cancel: 'Cancel',
    iagree: 'I Agree',
    //TOAST MESSAGES
    delete_success: 'Account deleted successfully.',
    enter_otp: 'Enter authentification to continue',
  },
  EditProfile: {
    edit_profile: 'Edit Profile',
    first_name: 'First Name',
    last_name: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    button_text_one: 'Send authentification message',
    button_text_two: 'Next',
    mobile_otp_verify: 'You Will Recieve A 6 Digit\nCode To Verify Next',
    verify: 'Verify',
    verified: 'Verified',
    address: 'Address',
    country: 'Country',
    nationality: 'Nationality',
    dob: 'Dob',
    select_country: 'Select Country',
    select_city: 'Select City',
    city: 'City',
    province: 'Province',
    tax_number: 'Tax Number / NIF / NIE',
    postalcode: 'Postal Code',
    share_code: 'Share Code',
    share_code_error: 'Share Code already exist!',

    //TOAST MESSAGES
    alert_firstname: 'Enter First Name',
    alert_lastname: 'Enter Last Name',
    alert_email: 'Enter email address',
    alert_mobile_number: 'Enter valid Mobile Number',
    alert_address: 'Enter Address',
    alert_city: 'Enter City',
    alert_country: 'Enter Country',
    alert_nationality: 'Enter Nationality',
    alert_postalcode: 'Enter valid Postal Code',
    alert_tax_number: 'Enter valid Tax Number',
    alert_share_code: 'Enter Share Code',

    mobile_otp_message: 'Authentification message has been sent to your phone.',
    invalid_otp: 'Invalid Authentification',
    otp_continue: 'Enter authentification to continue',
  },
  FriendProfile: {
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    sixty_pay: '+60 snipping from Pay',
    button_text_one: 'ADD TO CART',
    search_text: 'SEARCH IN WAXPLACE',
    share: 'Share',
    share_message: 'Get more exposure when you promote your gems.',
    balance: 'BALANCE',
    //TOAST MESSAGES
  },
  Friends: {
    search_text: 'SEARCH IN FRIENDS',
  },
  Login: {
    forgot_password: 'FORGOT PASSWORD',
    email: 'Email',
    button_text_one: 'Forgot password',
    welcome_back: 'Welcome Back, Please login to your account',
    signin_validate: "By Signing up, you agree to Waxplace's",
    terms: 'Terms and Conditions',
    privacy_policy: 'Privacy Policy',
    //TOAST MESSAGES
    alert_email: 'Please enter valid email address',
    password_sent: 'Password sent to your email.',
  },
  Maps: {
    waxmap: 'WAXMAP',
    location_permission: 'Allow WAXPLACE to use your location',
    permission_enable:
      'We can´t access your location! Click OK to open settings and enable',
    permission_enable_one: `Allow WAXPLACE to use your location`,
    get_started: "LET'S GO!",
    skip: 'SKIP',
    search_text: 'SEARCH IN WAXPLACE',
    button_text: 'Select this shop for pick up',
    //TOAST MESSAGE
    no_vendors: 'No vendors for pickup available',
    vendor_unavailable: 'Vendor unavailable for Pickup',
  },
  MyPurchases: {
    orderid: 'OrderID',
    order_date: 'Order Date',
    albums: 'Albums',
    total: 'Total Amt',
    search_text: 'SEARCH PURCHASES',
  },
  MySales: {
    order_id: 'Order ID',
    buyer: 'Buyer',
    cost: 'Album Cost',
    tax: 'Tax',
    net_sales: 'Net Sales',
    pickup_date: 'Pickup Date',
    order_status: 'Order Status',
    cancel: 'Cancel',
    pickup_details: 'Pickup Details',
    set_date: 'Set Date',
    set_time: 'Set Time',
    working_hours: 'Working Hours [ 9am - 5pm ]',
    available_from: 'Avalilable from',
    available_to: 'Available to',
    button_text_one: 'Accept',
    button_text_two: 'Select',
    button_text_three: 'Proceed',
    print_label: 'Print Label',
    tax_number: 'Tax Number / NIF / NIE',
    will_do_later: 'I will do it later',
    print_label: 'Print Label',
    customs_document: 'CUSTOMS DOCUMENT',
    customs_cn23: 'CUSTOMS CN23',

    //TOAST MESSAGES
    select_day: 'Please select a day within 7 days',
    from_time: 'From time should be between working hours',
    to_time: 'To time should be between working hours',
    search_text: 'SEARCH IN SALES',
    view_depots: 'View Depots',
    enter_tax_number: 'Please enter valid tax number / NIF / NIE',
    alert_tax_number: 'Enter valid Tax Number',
    invalid_postal_code: 'Invalid Postal code for sales',
  },
  Notifications: {
    search_text: 'NOTIFICATIONS',
  },
  OrderDetails: {
    search_text: 'SEARCH PURCHASES',
    invalid_share_code: 'Invalid share code',
    order_id: 'Order ID',
    payment_id: 'Payment ID',
    seller: 'Seller',
    cost: 'Album Cost',
    shipment_charge: 'Ship. Charge',
    tax: 'Tax',
    order_status: 'Order Status',
    help: 'Help',
    total: 'Total',
    //TOAST MESSAGE
    shipment_settings:
      'Shipment services not available in your location (zipcode). Change your profile settings.',
    album_continue: 'Please select an album to continue',
    view_depots: 'View Depots',
    print_label: 'Print Label',
  },
  PickupForUser: {
    tracking_id: 'Tracking ID',
    status: 'Status',
    inform_pickup: 'Inform Pickup',
    contact_info: 'Contact Info',
    button_text_one: 'Select',
    button_text_two: 'Proceed',
    pickup_details: 'Pickup Details',
    set_date: 'Set Date',
    set_time: 'Set Time',
    working_hours: 'Working Hours [ 9am - 5pm ]',
    store_details: 'Store Details',
    store_name: 'Store Name',
    address: 'Address',
    mobile_number: 'Mobile No',
    open_maps: 'Open in Maps',
    search_text: 'SEARCH IN PICKUPS',
  },
  Profile: {
    button_text_one: 'Cancel Subscription',
    button_text_two: 'COPY CODE',
    button_text_three: 'Share your Code',
    button_text_four: "LET'S GO!",
    button_text_five: 'Withdrawal Request',
    button_text_six: 'BUY NOW FOR ',
    button_text_seven: 'UPGRADE Now For €5,00pm',
    share_code_copied: 'Sharecode copied',
    share_code_not_added: 'Sharecode not added in Profile Settings',
    camera: 'CAMERA',
    gallery: 'GALLERY',
    share: 'SHARE',
    token_message: 'When someone uses your code you BOTH receive.',
    free_token: 'FREE TOKEN',
    your_share_code: 'Your Share Code',
    share_code_title: 'WAXPLACE SHARE CODE',
    share_code_subject: 'SHARE CODE FOR WAXPLACE',
    share_code_message: 'Share Code : ',
    profile: 'PROFILE',
    skip: 'SKIP',
    withdraw: 'WITHDRAW',
    withdraw_message: `Please note that the withdrawal process typically takes a maximum of 48 hours to process. We strive to ensure quick and efficient processing of your withdrawal requests`,
    amount: 'Amount',
    purchase_tokens: 'PURCHASE TOKENS',
    appear_featured: 'APPEAR IN FEATURED ITEMS',
    featured_message:
      'Get more exposure when you poromote your items, sell faster etc etc bla bla . You know its worth it and all of that.',
    featured_items: 'FEATURED ITEMS',
    your_track: 'YOUR TRACK',
    ten_tokens: '10 TOKENS',
    twenty_tokens: '20 TOKENS',
    thirty_tokens: '30 TOKENS',
    save28: '',
    save39: '',
    wallet: 'Wallet',
    subscription_title: 'FOR ACCESS TO 24HR UPGRADE NOW!',
    recieve: 'RECIEVE',
    subscription_message_one: 'TOKENS TO APPEAR IN \nFEAUTURED ITEMS.',
    subscription_message_two:
      'GET 24 HOUR ACCESS TO VINYL BEFORE ANY OTHER USERS',
    twentyfour_access: '24 HOUR ACCESS',
    collection_value: 'COLLECTION VALUE',
    wallet: 'WALLET',
    tokens: 'TOKENS',
    collections: 'COLLECTIONS',
    wishlist: 'WISH LIST',
    pickups: 'PICK UPS',
    my_sales: 'MY SALES',
    my_purchases: 'MY PURCHASES',
    friends: 'FRIENDS',
    waxdrop_create: 'WAX DROP CREATE',
    already_subscribed_message: 'ALREADY SUBSCRIBED',
    become_premium: '24HR ACCESS',
    notifications: 'NOTIFICATIONS',
    categories: 'CATEGORIES',
    edit_profile: 'EDIT PROFILE',
    payment_settings: 'PAYMENT SETTINGS',
    share_earn: 'SHARE & EARN',
    settings: 'SETTINGS',
    help_faq: 'HELP & FAQ',
    contact_us: 'CONTACT US',
    tnc: 'TERMS AND CONDITIONS',
    mnc:'MANGOPAY TERMS AND CONDITIONS',
    logout_text: 'LOGOUT',
    //TOAST MESSAGES
    empty_purchase: 'My Purchases is empty',
    empty_sales: 'My Sales is empty',
    no_pickups: 'No pickups are available',
    empty_wishlist: 'Wishlist is empty',
    empty_collections: `${'Collections'} is empty`,
    profile_success: 'Profile updated successfully',
    logout: 'Are you sure you want to logout? Come back soon! :)',
    cancel: 'cancel',
    confirm: 'confirm',
    select_tokens: 'Select tokens',
    no_friends: "You haven't added any friends yet",
    empty_notifications: 'Notifications is empty',
    subscription_updated: 'User Subscription Cancelled',
    subscription_status: 'Subscription Status',
    subscription_cancel: 'Do you wish to cancel your subscription ?',
    already_subscribed: 'The user is already subscribed',
    invalid_withdrawal: 'Invalid withdrawal request',
  },
  ProfileWeeklyDrops: {
    search_text: 'SEARCH IN WAX DROPS',
    weekly_drop: 'Weekly Drop Archive',
    weekly_drops_title: 'Want to do a weekly drop?',
    weekly_drops_message:
      "Our weekly selection of the finest uploads of week. Expert to hear music from Dj's",
    weekly_drops_placeholder: 'Tell us about your favourite music',
    button_text: 'Send',
    //TOAST MESSAGE
    alert_message: 'Please enter the message',
  },
  Registration: {
    button_text: 'Next',
    button_text_one: 'Select',
    button_text_two: 'Go Back',
    first_name: 'First Name',
    last_name: 'Last Name',
    email: 'Email',

    email_exists: 'email already exist!',
    otp_verify: 'You Will Recieve A 6 Digit\nCode To Verify Next',
    verify: 'Verify Email',
    verified: 'Verified',
    phone: 'Phone',
    address: 'Address',
    country: 'Country',
    nationality: 'Nationality',
    dob: 'Dob',
    city: 'City',
    province: 'Province',
    postalcode: 'Postal Code',
    tax_number: 'Tax Number / NIF / NIE',
    share_code: 'Share Code',
    share_code_exists: 'Share Code already exist!',
    invalid_otp: 'Invalid Authentification',
    //TOAST MESSAGE
    alert_firstname: 'Enter First Name',
    alert_lastname: 'Enter Last Name',
    alert_email: 'Enter email address',
    alert_mobile_number: 'Enter valid Mobile Number',
    alert_address: 'Enter Address',
    alert_city: 'Enter City',
    alert_country: 'Enter Country',
    alert_postalcode: 'Enter valid Postal Code',
    alert_postalcode_islands:
      'Islands of Spain are unavailabe for the timebeing',
    alert_tax_number: 'Enter valid Tax Number',
    alert_share_code: 'Enter valid Share Code',
    alert_province: 'Enter Province',
    otp_invalid: 'Invalid Authentification',
    otp_continue: 'Enter authentification to continue',
    currently_spain:
      'Currently mobile number from spain can only be registered',
    invalid_email: 'Invalid Email',
  },
  Settings: {
    button_text_one: 'ADD DETAILS',
    button_text_two: 'CHANGE PASSWORD',
    bank_details: 'BANK DETAILS',
    account_number: 'Account number',
    re_account_number: 'Re-Enter Account number',
    iban: 'IBAN',
    change_password: 'CHANGE PASSWORD',
    old_password: 'Old Password',
    new_password: 'New Password',
    re_new_password: 'Re-Enter Password',
    go_premium: 'GET 24h ACCESS',
    label_one:
      'Preselected vinyl Viewings Based on your Collection,Category & APP Behaviour',
    label_two: 'Never miss a package.',
    label_three: 'Support local shops.',
    label_four: 'Cheaper dealer.',
    email_notifications: 'EMAIL NOTIFICATIONS',
    delete_account_message: 'DELETE ACCOUNT',
    other_notifications: 'Other Notifications',
    new_followers: 'New followers',
    wishlist: 'Wish List',
    new_items: 'New Items',
    remainders: 'Reminders',
    marketing: 'Marketing',
    informative: 'Informative',
    gps: 'GPS',
    delete_account: 'Do you wish to delete your account?',
    iagree: 'I Agree',
    cancel: 'Cancel',
    //TOAST MESSAGE
    alert_old_password: 'Please enter old password',
    alert_new_password: 'Please enter new password',
    alert_re_new_password: 'Please enter new password',
    password_mismatch: "Password doesn't match",
  },
  StoreDetails: {
    open_today: 'Open Today',
    closed: 'Closed',
    sixty_pay: '+60 snipping from Pay',
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    add_to_cart: 'ADD TO CART',
    waxplace: 'WAXPLACE',
    search_text: 'SEARCH IN STORE',
    sunday: 'SUNDAY',
    monday: 'MONDAY',
    tuesday: 'TUESDAY',
    wednesday: 'WEDNESDAY',
    thursday: 'THURSDAY',
    friday: 'FRIDAY',
    saturday: 'SATURDAY',
    //TOAST MESSAGE
    location_permission: 'Please grant WAXPLACE access to use the location',
    permission_enable:
      'We can´t access your location! Click OK to open settings and enable',
    permission_enable_one: `Allow WAXPLACE to use your location`,
  },
  WalletHistory: {
    button_text: 'Withdrawal Request',
    search_text: 'WALLET HISTORY',
    withdraw_funds: 'Withdraw Funds',
    withdraw: 'WITHDRAW',
    withdraw_message: `Please note that the withdrawal process typically takes a maximum of 48 hours to process. We strive to ensure quick and efficient processing of your withdrawal requests`,
    withdrawal_message: 'Withdrawal request sent successfully',
    amount: 'Amount',
    invalid_withdrawal: 'Invalid withdrawal request',
    update_kyc_bank_account:
      'Please do KYC and add a bank account in Payment Settings',
    empty_text_today: 'No wallet history available for today',
    empty_text_last_week: 'No wallet history available last week',
    empty_text_all_data: 'No wallet history available',
  },
  WeeklyDrop: {
    button_text: 'Send',
    weekly_drop: 'Weekly Drop',
    weekly_drop_message:
      'Our weekly selection of the finest uploads of the week.Expect to hear music from diggers all over the world.',
    play_all: 'Play All',
    recent_drops: 'Recent Drops',
    want_weekly_drops: 'Want to do a weekly drop?',
    search_text: 'SEARCH IN WAX DROPS',

    //TOAST MESSAGE
    alert_message: 'Please enter the message',
    weekly_drops_success: 'Weekly drop request sent successfully',
  },
  WishList: {
    media_condition: 'Media',
    sleeve_condition: 'Sleeve',
    remove: 'REMOVE',
    add_to_cart: 'ADD TO CART',
    search_text: 'SEARCH IN WISHLIST',
  },
  NearbyDepots: {
    correos_depots: 'CORREOS INFO',
  },
};

export default en;
